CREATE TABLE order_lines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    UUID NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    item_id     UUID NOT NULL REFERENCES items (id),
    qty         INT NOT NULL CHECK (qty > 0),
    price_cents BIGINT NOT NULL CHECK (price_cents >= 0)
);

CREATE INDEX idx_order_lines_order_id ON order_lines (order_id);
