// Code generated by 'yaegi extract cosy-console/internal/domain/catalog/models'. DO NOT EDIT.

//go:build go1.27
// +build go1.27

package symbols

import (
	"cosy-console/internal/domain/catalog/models"
	"reflect"
)

func init() {
	Symbols["cosy-console/internal/domain/catalog/models/models"] = map[string]reflect.Value{
		// type definitions
		"Item": reflect.ValueOf((*models.Item)(nil)),
	}
}
