// Code generated by 'yaegi extract cosy-console/internal/domain/catalog'. DO NOT EDIT.

//go:build go1.27
// +build go1.27

package symbols

import (
	"cosy-console/internal/domain/catalog"
	"reflect"
)

func init() {
	Symbols["cosy-console/internal/domain/catalog/catalog"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrNotFound": reflect.ValueOf(&catalog.ErrNotFound).Elem(),

		// type definitions
		"ItemFilter": reflect.ValueOf((*catalog.ItemFilter)(nil)),
	}
}
