// Code generated by 'yaegi extract cosy-console/internal/domain/orders'. DO NOT EDIT.

//go:build go1.27
// +build go1.27

package symbols

import (
	"cosy-console/internal/domain/orders"
	"reflect"
)

func init() {
	Symbols["cosy-console/internal/domain/orders/orders"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrInvalidTransition": reflect.ValueOf(&orders.ErrInvalidTransition).Elem(),
		"ErrNotFound":          reflect.ValueOf(&orders.ErrNotFound).Elem(),

		// type definitions
		"CreationParams": reflect.ValueOf((*orders.CreationParams)(nil)),
		"LineInput":      reflect.ValueOf((*orders.LineInput)(nil)),
		"OrderFilter":    reflect.ValueOf((*orders.OrderFilter)(nil)),
		"PricedLine":     reflect.ValueOf((*orders.PricedLine)(nil)),
		"UpdateAttrs":    reflect.ValueOf((*orders.UpdateAttrs)(nil)),
	}
}
