// Code generated by 'yaegi extract cosy-console/internal/domain/orders/models'. DO NOT EDIT.

//go:build go1.27
// +build go1.27

package symbols

import (
	"cosy-console/internal/domain/orders/models"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["cosy-console/internal/domain/orders/models/models"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"StatusCancelled": reflect.ValueOf(constant.MakeFromLiteral("\"cancelled\"", token.STRING, 0)),
		"StatusDelivered": reflect.ValueOf(constant.MakeFromLiteral("\"delivered\"", token.STRING, 0)),
		"StatusPaid":      reflect.ValueOf(constant.MakeFromLiteral("\"paid\"", token.STRING, 0)),
		"StatusPending":   reflect.ValueOf(constant.MakeFromLiteral("\"pending\"", token.STRING, 0)),
		"StatusShipped":   reflect.ValueOf(constant.MakeFromLiteral("\"shipped\"", token.STRING, 0)),

		// type definitions
		"Order":     reflect.ValueOf((*models.Order)(nil)),
		"OrderLine": reflect.ValueOf((*models.OrderLine)(nil)),
	}
}
